// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVPw2K7-KXv4vyEnW_-g5aatBjDV9A-Hs',
    appId: '1:220862448660:web:6c5095bfdf0a2394895301',
    messagingSenderId: '220862448660',
    projectId: 'dineflow-hackathon',
    authDomain: 'dineflow-hackathon.firebaseapp.com',
    storageBucket: 'dineflow-hackathon.firebasestorage.app',
    measurementId: 'G-ERK1VS75HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2uO1nDYerBDj9vRYvu-pXJ0mTh3whgAQ',
    appId: '1:220862448660:android:57d9c215eb32a969895301',
    messagingSenderId: '220862448660',
    projectId: 'dineflow-hackathon',
    storageBucket: 'dineflow-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4O08NrvzxyuDmTS1wGJ0VZ8A9__3HbCE',
    appId: '1:220862448660:ios:5d159938ce0e17d5895301',
    messagingSenderId: '220862448660',
    projectId: 'dineflow-hackathon',
    storageBucket: 'dineflow-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.dineflowManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4O08NrvzxyuDmTS1wGJ0VZ8A9__3HbCE',
    appId: '1:220862448660:ios:5d159938ce0e17d5895301',
    messagingSenderId: '220862448660',
    projectId: 'dineflow-hackathon',
    storageBucket: 'dineflow-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.dineflowManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVPw2K7-KXv4vyEnW_-g5aatBjDV9A-Hs',
    appId: '1:220862448660:web:25438b1ef6553342895301',
    messagingSenderId: '220862448660',
    projectId: 'dineflow-hackathon',
    authDomain: 'dineflow-hackathon.firebaseapp.com',
    storageBucket: 'dineflow-hackathon.firebasestorage.app',
    measurementId: 'G-NL31NLB78D',
  );

}